### ISSUE TITLE
关闭下拉刷新时，重复刷新报错

### ISSUE THREAD

**Issue by 18y** [dailc/pullToRefresh-h5-iscroll#1]
文件：demo_pullRefresh_skin_default.html
js:	window.onload = function() {
			demoPullToRefresh.init(PullToRefreshSkinDefault,false,true);
	};
开启下拉刷新时没有问题，关闭时连续刷新报错
![image](https://cloud.githubusercontent.com/assets/22790765/26185735/60d6b98a-3bbf-11e7-93f5-6266814e3735.png)

**Comment by dailc** [comment]
已经解决！

**Comment by dailc** [comment]
修复！
